version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-production
    container_name: career-solutions-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=./database.sqlite
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend/database.sqlite:/app/backend/database.sqlite
    networks:
      - career-solutions-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: career-solutions-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      - backend
    networks:
      - career-solutions-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: career-solutions-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - career-solutions-network
    restart: unless-stopped

networks:
  career-solutions-network:
    driver: bridge

volumes:
  database:
    driver: local 