exports.seed = function(knex) {
  return knex('success_stories').del()
    .then(function () {
      return knex('success_stories').insert([
        { user_id: 1, title: 'Hired by Royal Caribbean as Assistant Waiter', story: 'Douglas Chikwira was hired by Royal Caribbean as an Assistant Waiter. "Career Solutions made my dream come true!"', image_url: '/images/douglas.jpg', created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 2, title: 'Hired by Cunard as Assistant Waiter', story: 'Nathanie Meke joined Cunard as an Assistant Waiter. "Thank you for the support and guidance!"', image_url: '/images/nathanie.jpg', created_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 3, title: 'Hired by Carnival Cruise as Assistant Waiter', story: 'Yolanda Jambo started her career with Carnival Cruise as an Assistant Waiter. "I am grateful for this opportunity!"', image_url: '/images/yolanda.jpg', created_at: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 4, title: 'Hired by Sean Carroll Trucks, Ireland as HGV Driver', story: 'Daniel Majuru is now an HGV Driver at Sean Carroll Trucks in Ireland. "A life-changing move for me and my family!"', image_url: '/images/daniel.jpg', created_at: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 5, title: 'Hired by Rosteka Trucks, Poland as Truck Driver', story: 'Tinashe Mpunga joined Rosteka Trucks in Poland as a Truck Driver. "Thank you for making this possible!"', image_url: '/images/tinashe.jpg', created_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 6, title: 'Hired by Princcess Cruise Line as Housekeeper', story: 'Thilda Mutsago is now a Housekeeper at Princcess Cruise Line. "I am so happy to start this new journey!"', image_url: '/images/thilda.jpg', created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 7, title: 'Hired in UAE as Hostess', story: 'Sharleen Nziradzarwo secured a Hostess position in the UAE. "This is a dream come true!"', image_url: '/images/sharleen.jpg', created_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 8, title: 'Hired by Carnival as Waiter', story: 'Ernest Chikwira is now a Waiter at Carnival. "Thank you for your help!"', image_url: '/images/ernest.jpg', created_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 9, title: 'Hired by Disney Cruise Lines as Waiter', story: 'Lekhuthaba Moyo joined Disney Cruise Lines as a Waiter. "I am excited for this new adventure!"', image_url: '/images/lekhuthaba.jpg', created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
        { user_id: 10, title: 'Hired in UAE as Sommelier', story: 'Leo Karume is now a Sommelier in the UAE. "Thank you for believing in me!"', image_url: '/images/leo.jpg', created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(), updated_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() }
      ]);
    });
}; 